# Generated by Django 4.1 on 2023-01-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleQuestion', models.CharField(max_length=100)),
                ('subtitleQuestion', models.CharField(max_length=100)),
                ('descriptionQuestion', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
