# Generated by Django 4.1 on 2023-01-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='imageQuestion',
            field=models.ImageField(blank=True, upload_to='questions/images'),
        ),
    ]
