# Generated by Django 4.1 on 2023-01-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_image_question_imagequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='imageQuestion',
            new_name='image',
        ),
    ]
