# Generated by Django 4.1 on 2023-01-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloP', models.CharField(max_length=100)),
                ('descripcionP', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='profiles')),
            ],
        ),
    ]
