# Generated by Django 4.1 on 2023-01-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_preguntas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
