# Generated by Django 4.1 on 2023-01-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleS', models.CharField(max_length=100)),
                ('descriptionS', models.CharField(max_length=250)),
                ('detallesS', models.CharField(max_length=100)),
                ('imageS', models.ImageField(upload_to='servicios/images')),
            ],
        ),
    ]
