# Generated by Django 4.1 on 2023-01-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='precio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
